// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class ACTEURFILM
{
    public decimal FK_IDFILM { get; set; }

    public decimal FK_IDACTEUR { get; set; }

    public virtual ACTEUR FK_IDACTEURNavigation { get; set; }

    public virtual FILM FK_IDFILMNavigation { get; set; }
}