// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class ACTEUR
{
    public decimal IDARTISTE { get; set; }

    public virtual ICollection<ACTEURFILM> ACTEURFILM { get; set; } = new List<ACTEURFILM>();

    public virtual ARTISTE IDARTISTENavigation { get; set; }

    public virtual ICollection<PERSONNAGE> PERSONNAGE { get; set; } = new List<PERSONNAGE>();
}