// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class ADRESSE
{
    public decimal IDADRESSE { get; set; }

    public string LIGNEADRESSE { get; set; }

    public string VILLE { get; set; }

    public string PROVINCE { get; set; }

    public string CODEPOSTAL { get; set; }

    public decimal FK_IDUTILISATEUR { get; set; }

    public virtual UTILISATEUR FK_IDUTILISATEURNavigation { get; set; }
}