// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class CARTECREDIT
{
    public string NUMCARTE { get; set; }

    public string TYPECARTE { get; set; }

    public DateTime DATEEXPIRATION { get; set; }

    public decimal CVV { get; set; }

    public decimal FK_IDCLIENT { get; set; }

    public virtual CLIENT FK_IDCLIENTNavigation { get; set; }
}