// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class EMPLOYE
{
    public decimal IDUTILISATEUR { get; set; }

    public decimal MATRICULE { get; set; }

    public virtual UTILISATEUR IDUTILISATEURNavigation { get; set; }
}