// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class ETL_LOCATION
{
    public decimal ID_ETL_LOCATION { get; set; }

    public decimal IDUTILISATEUR { get; set; }

    public decimal IDFILM { get; set; }

    public decimal IDTEMPS { get; set; }

    public virtual ETL_FILM IDFILMNavigation { get; set; }

    public virtual ETL_TEMPS IDTEMPSNavigation { get; set; }

    public virtual ETL_CLIENT IDUTILISATEURNavigation { get; set; }
}