// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class EXEMPLAIRE
{
    public decimal IDEXEMPLAIRE { get; set; }

    public decimal FK_IDFILM { get; set; }

    public string LOUE { get; set; }

    public virtual FILM FK_IDFILMNavigation { get; set; }

    public virtual ICollection<LOCATION> LOCATION { get; set; } = new List<LOCATION>();
}