// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class FILM
{
    public decimal IDFILM { get; set; }

    public string TITRE { get; set; }

    public decimal ANNEE { get; set; }

    public string PAYS { get; set; }

    public string LANGUEORIGINALE { get; set; }

    public decimal DUREE { get; set; }

    public string RESUME { get; set; }

    public string AFFICHE { get; set; }

    public string LIENSBANDEANNONCE { get; set; }

    public decimal? FK_IDREALISATEUR { get; set; }

    public virtual ICollection<ACTEURFILM> ACTEURFILM { get; set; } = new List<ACTEURFILM>();

    public virtual ICollection<EXEMPLAIRE> EXEMPLAIRE { get; set; } = new List<EXEMPLAIRE>();

    public virtual REALISATEUR FK_IDREALISATEURNavigation { get; set; }

    public virtual ICollection<GENREFILM> GENREFILM { get; set; } = new List<GENREFILM>();

    public virtual ICollection<PERSONNAGE> PERSONNAGE { get; set; } = new List<PERSONNAGE>();

    public virtual ICollection<SCENARISTEFILM> SCENARISTEFILM { get; set; } = new List<SCENARISTEFILM>();
}