// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class FORFAIT
{
    public string CODEFORFAIT { get; set; }

    public string NOM { get; set; }

    public decimal COUT { get; set; }

    public decimal NBLOCATIONMAX { get; set; }

    public decimal? DUREEMAX { get; set; }

    public virtual ICollection<CLIENT> CLIENT { get; set; } = new List<CLIENT>();
}