// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class GENREFILM
{
    public decimal FK_IDFILM { get; set; }

    public decimal FK_IDGENRE { get; set; }

    public virtual FILM FK_IDFILMNavigation { get; set; }

    public virtual GENRE FK_IDGENRENavigation { get; set; }
}