// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class SCENARISTE
{
    public decimal IDSCENARISTE { get; set; }

    public string NOM { get; set; }

    public virtual ICollection<SCENARISTEFILM> SCENARISTEFILM { get; set; } = new List<SCENARISTEFILM>();
}