// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class UTILISATEUR
{
    public decimal IDUTILISATEUR { get; set; }

    public string NOM { get; set; }

    public string ADRESSECOURRIEL { get; set; }

    public string NOTELEPHONE { get; set; }

    public DateTime DATENAISSANCE { get; set; }

    public string MOTDEPASSE { get; set; }

    public virtual ICollection<ADRESSE> ADRESSE { get; set; } = new List<ADRESSE>();

    public virtual CLIENT CLIENT { get; set; }

    public virtual EMPLOYE EMPLOYE { get; set; }
}