// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class VUE_MAT_CORRELATION
{
    public decimal? FILMID1 { get; set; }

    public decimal? FILMID2 { get; set; }

    public decimal? CORRELATION { get; set; }
}