// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webflix.Models;

public partial class VUE_MAT_MOYENNE_COTE
{
    public decimal? AVG_COTE { get; set; }

    public decimal? IDFILM { get; set; }
}